### ISSUE TITLE
Example Lacking Details

### ISSUE THREAD

**Issue by cgountanis** [mikepc/jwt-dotnet-core-2.0#3]
I am not seeing how you auth anywhere. I see the setup and controller Authorize annotations but how do you save the token to header for all subsequent calls? Not sure if I am missing something.

**Comment by mikepc** [comment]
This is to demonstrate Authorizing the token via middleware, not authenticating credentials and creating one.

**Comment by cgountanis** [comment]
I hear you. Just would be nice to show how it gets passed to the header, not do much created, plenty of help there. Although a free more examples and you would have the full picture. I am still trying to figure out what SaveToken actually does with the .AddJwtBearer.

**Comment by mikepc** [comment]
Oh absolutely!

Authorization: Bearer BASE64_TOKEN_TEXT_HERE as part of the HTTP header

example:

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
